# Num-Ex 예제
## 시퀀스 데이터로부터 배열 생성

In [1]:
import numpy as np

In [2]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [3]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [4]:
a1.dtype

dtype('int32')

In [5]:
a2.dtype

dtype('float64')

In [6]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [7]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 범위를 지정해 배열 생성

1. arr_obj = np.arange([start, ] stop[, step])
    - start부터 stop 전까지 step만큼 더해 배열을 생성
    - start 디폴트는 0
    - step 디폴트는 1

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
a1 = np.arange(1, 10)
a1.shape

(9,)

In [13]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2.shape

(3, 3)

In [14]:
np.arange(12). reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
b1 = np.arange(12).reshape(4, 3)
b1.shape

(4, 3)

In [16]:
b2 = np.arange(5)
b2.shape

(5,)

2. arr_obj = np.linspace(start, stop[, num])
    - start부터 stop까지(포함) num개의 NumPy 배열 생성
    - num 디폴트 값은 1

In [17]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

# 특별한 형태의 배열 생성

- arr_zero_n = np.zeros(n)
- arr_zero_mxn = np.zeros((m,n))
    - 원소가 0인 배열 생성
- arr_one_n = np.ones(n)
- arr_one_mxn = np.ones((m,n))
    - 원소가 1인 배열 생성

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.zeros((3, 4, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 배열의 데이터 타입 변환, 연산

In [25]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])  # 문자열

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [26]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)  # 실수로 변환
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [27]:
str_a1.dtype  # 문자열

dtype('<U5')

In [28]:
num_a1.dtype  # 실수

dtype('float64')

In [29]:
np.random.rand(2, 3)

array([[0.42785601, 0.22716958, 0.45678763],
       [0.35393533, 0.41344141, 0.15469668]])

In [30]:
np.random.rand()

0.27818860032969217

In [31]:
np.random.rand(2, 3, 4)

array([[[0.03827523, 0.14050965, 0.59325794, 0.8575015 ],
        [0.78527995, 0.9499118 , 0.71582164, 0.76700871],
        [0.54897524, 0.49841986, 0.50823211, 0.68576686]],

       [[0.67590986, 0.4716914 , 0.94670285, 0.1877611 ],
        [0.87199851, 0.44819554, 0.23469772, 0.87213353],
        [0.45972722, 0.94656639, 0.55321972, 0.59187861]]])

In [32]:
arr1 = np.array([10, 20, 30, 40])  # 요소끼리 더하기
arr2 = np.array([1, 2, 3, 4])
arr1 + arr2

array([11, 22, 33, 44])

In [33]:
arr2 * 2  # 모든 요소에 *2

array([2, 4, 6, 8])

In [34]:
arr2 ** 2  # 요소 제곱 연산

array([ 1,  4,  9, 16], dtype=int32)

In [35]:
arr1 * arr2  # 요소끼리 곱하기

array([ 10,  40,  90, 160])

In [36]:
arr1 / arr2

array([10., 10., 10., 10.])

In [38]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

# 배열의 인덱싱과 슬라이싱

In [39]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [40]:
a1[0]

0

In [41]:
a1[4]

40

In [42]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [43]:
a1[[0, 3, 4]]  # 해당 차원의 여러 원소 선택

array([ 0, 30, 40])

In [44]:
a2 = np.arange(10, 100, 10).reshape(3, 3)

In [45]:
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [46]:
a2[0, 2]

30

In [47]:
a2[2, 2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [48]:
a2[1]  # 2차원 배열에서 행 하나 출력

array([40, 50, 60])

In [49]:
a2[1] = 0  # 행 전체 0으로 변경

In [50]:
a2

array([[10, 20, 30],
       [ 0,  0,  0],
       [70, 80, 95]])

In [51]:
a2[[0, 2], [0, 1]]  # 0행 0열, 2행 1열 출력

array([10, 80])

In [53]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]  # 1부터 4까지

array([10, 20, 30])

In [54]:
b1[2:]  # 2부터 끝까지

array([20, 30, 40, 50])

In [55]:
b1[2:5] = np.array([25, 35, 45])  # 배열 대입 연산 가능
b1

array([ 0, 10, 25, 35, 45, 50])

In [57]:
a2[1:2, 1:]  # crop이랑 비슷한 기능 범위 지정해서 잘라내기

array([[0, 0]])