# Num-Ex 예제
## 시퀀스 데이터로부터 배열 생성

In [1]:
import numpy as np

In [9]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [4]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [6]:
a1.dtype

dtype('float64')

In [7]:
a2.dtype

dtype('float64')

In [8]:
a1.dtype

dtype('float64')

In [10]:
a1.dtype

dtype('int32')

In [11]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [18]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 범위를 지정해 배열 생성

1.arr_obj = np.arange([start, ] stop[, step])
- start부터 stop 전까지 step만큼 더해 배열을 생성
- start 디폴트는 0
- step 디폴트는 1

In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
a1 = np.arange(1,10)
a1.shape

(9,)

In [22]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2.shape

(3, 3)

In [23]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [25]:
b2 = np.arange(5)
b2.shape

(5,)

# 범위를 지정해 배열 생성

arr_obj = np.linspace(start, stop[, num])
- start부터 stop까지(포함) num개의 NumPy 배열 생성
- num 디폴트 값은 1

In [26]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

특별한 형태의 배열 생성
- arr_zero_n = np.zeros(n)
- arr_zero_mxn = np.zeros((m,n))
 -  원소가 0인 배열 생성
- arr_one_n = np.ones(n)
- arr_one_mxn = np.ones((m,n))
 -  원소가 1인 배열 생성

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [34]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 배열의 데이터 타입 변환

In [37]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])#문자열이다 8비트로 표현되는 유니코드다

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [38]:
str_a1 = np.array(['1.567', '0.123','5.123', '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [39]:
str_a1.dtype

dtype('<U5')

In [40]:
num_a1.dtype

dtype('float64')

In [43]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [45]:
[arr3.sum(),arr3.mean()]

[10, 2.0]